# Generated by Django 5.2.10 on 2026-01-29 17:19

import django.core.validators
import django.db.models.deletion
import messenger.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nickname', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_token'], name='sessions_session_7633cd_idx'), models.Index(fields=['ip_address'], name='sessions_ip_addr_8b9606_idx'), models.Index(fields=['is_banned', 'banned_until'], name='sessions_is_bann_af7fb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=messenger.models.generate_room_code, editable=False, max_length=8, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_retention_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('owner_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_rooms', to='messenger.session')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reported_count', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.room')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messenger.session')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BannedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('banned_by', models.CharField(max_length=100)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='messenger.session')),
            ],
            options={
                'db_table': 'banned_sessions',
                'ordering': ['-banned_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Session Created'), ('room_create', 'Room Created'), ('room_join', 'Room Joined'), ('message_send', 'Message Sent'), ('rate_limit', 'Rate Limit Hit'), ('admin_action', 'Admin Action'), ('session_ban', 'Session Banned'), ('message_report', 'Message Reported'), ('room_delete', 'Room Deleted')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='messenger.room')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='messenger.session')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['code'], name='rooms_code_10ba66_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active', 'created_at'], name='rooms_is_acti_e298ac_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'timestamp'], name='messages_room_id_4380e2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session'], name='messages_session_6f7ead_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted', 'timestamp'], name='messages_is_dele_5bad0b_idx'),
        ),
        migrations.AddIndex(
            model_name='bannedsession',
            index=models.Index(fields=['session', 'expires_at'], name='banned_sess_session_cac566_idx'),
        ),
        migrations.AddIndex(
            model_name='bannedsession',
            index=models.Index(fields=['banned_at'], name='banned_sess_banned__b9c6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='audit_logs_event_t_222f56_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['session'], name='audit_logs_session_632f07_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='audit_logs_ip_addr_932507_idx'),
        ),
    ]
